version: '3.8'

services:
    server:
        build: .
        volumes:
            - .:/usr/src/app
            - node-modules:/usr/src/app/node_modules
        ports:
            - 8000:8000
            - 9229:9229
        command: yarn dev
    test-db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        volumes:
            - test-db-data:/var/lib/postgresql/data
volumes:
    node-modules:
    test-db-data:
